#!/usr/bin/expect  
set timeout 30  
if { [llength $argv] < 3 } {
    puts "Usage:"
    puts "    $argv0 ip_index local_path remote_path"
    puts "    for example: $argv0 26 ./xx /dev/null"
    puts "    will execute scp -r ./xx root@192.168.3.26:/dev/null"
    exit 1
}
set ip_index [lindex $argv 0]
set local_path [lindex $argv 1]
set remote_path [lindex $argv 2]
set port 21000
set passwd 4TiOq6yXHncIy6F
spawn scp -P $port -r $local_path root@192.168.3.$ip_index:$remote_path
expect {  
        "(yes/no)?"  
        {send "yes\n";exp_continue}  
        "password:"  
        {send "$passwd\n"}  
}  
interact
