#!/usr/bin/expect
set online_ip {
    {58.67.200.176 GZ_MASTER1}
    {58.67.200.177 GZ_MASTER2}
    {210.14.141.201 BJ_SLAVE}
    {116.211.100.82 WH_JXDX_ROOT}
    {220.249.103.153 WH_LXLT_ROOT}
    {112.82.242.38 JS_CZLT_STORE}
    {112.82.242.39 JS_CZLT_STORE}
    {116.211.100.83 WH_JXDX_STORE}
    {116.211.100.84 WH_JXDX_STORE}
    {116.211.100.85 WH_JXDX_STORE}
    {116.211.100.88 WH_JXDX_STORE}
    {116.211.100.89 WH_JXDX_STORE}
    {220.249.103.133 WH_LXLT_STORE}
    {220.249.103.154 WH_LXLT_STORE}
    {220.249.103.155 WH_LXLT_STORE}
    {61.160.196.230 JS_CZDX_STORE}
    {61.160.196.231 JS_CZDX_STORE}
    {61.160.196.232 JS_CZDX_STORE}
}

proc usage { cmd } {
    global online_ip
    puts "usage:"
    puts "    $cmd ip_index"
    puts "ip information:"
    puts [format "%-6s %-16s %s" index ip msg]
    puts "-----------------------------------"
    set i 0
    foreach ip_info $online_ip {
        set ip [lindex $ip_info 0]
        set msg [lindex $ip_info 1]
        puts [format "%-6s %-16s %s" $i $ip $msg]
        incr i
    }

}

if {$argc < 1} {
    usage $argv0
    exit 1
}
if {[lindex $argv 0]=="-h"} {
    usage $argv0
    exit 1
}
set ip_index [lindex $argv 0]
if {$ip_index < 0 || $ip_index >= [llength $online_ip]} {
    puts "ip_index:$ip_index error"
    usage $argv0
    exit 1
}

set ip_info [lindex $online_ip $ip_index]
set ip [lindex $ip_info 0]
set port 27100
set user bt_user
set passwd bitqiu_2016
spawn ssh -p $port $user@$ip
expect {
    "(yes/no)?"
    {send "yes\n";exp_continue}
    "password:"
    {send "$passwd\n"}
}
interact
